### ISSUE TITLE
Improper Use of Index as Key in React List Rendering

### ISSUE THREAD

**Issue by cn10xdev** [cn10xdev/react-express-starter#10]
The map() function in the Customers component uses the array index as the key instead of a unique customer ID. This could lead to potential issues with rendering efficiency and reordering. The goal is to switch to a unique identifier without giving away the answer.

**Comment by Vivek1235** [comment]
Hi, I'd like to work on this issue if no one else is currently assigned to it. My plan is to replace the array index used as the key in the **Customers** component with a unique identifier, such as `customer.id`. Let me know if you have any specific preferences or guidelines I should follow. 

Looking forward to contributing!

**Comment by rishavd3v** [comment]
Hey, if this issue is not assigned to anyone, I'd like to work on it. Using array indices as keys can introduce potential issues with rendering efficiency and UI consistency especially when the list of customers is reordered or modified.

**Comment by rishavd3v** [comment]
@cn10xdev thanks for assigning the issue to me. Made a PR (#12) please have a look.

**Comment by rishavd3v** [comment]
Thanks for the opportunity to contribute! Can you please add "hacktoberfest" or hacktoberfest-accepted" label to the issue? "HacktoberFest24" is not a valid tag.

**Comment by cn10xdev** [comment]
sure

**Comment by rishavd3v** [comment]
Thanks, but it still doesn't seem to count it towards hacktoberfest contribution! I think it is important for the repo to have 'hacktoberfest' label to be eligible.
