### ISSUE TITLE
Overwriting customers State Without Handling Fetch Errors

### ISSUE THREAD

**Issue by cn10xdev** [cn10xdev/react-express-starter#8]
In the fetch call within componentDidMount, an error in the fetch process will result in the customers state being overwritten, but the error itself isn't properly handled. This might confuse the user with no error feedback. A better error-handling mechanism is required.

**Comment by rishavd3v** [comment]
Hey, I would like to work on this issue. I propose to improve the error handling by displaying a user-friendly error message when the fetch fails. This way, users will know there's an issue with loading the data instead of just seeing an empty list. Let me know if I can take this on!

**Comment by rishavd3v** [comment]
@cn10xdev Opened a PR (#13). Please have a look and let me know if any changes are required!
